name: Flow CLI Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run workflow every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit
      # and push the added or changed files to the repository.
      contents: write
    steps:
      - name: Check Release
        run: |
          flow_cli_version="$(curl -s 'https://api.github.com/repos/onflow/flow-cli/releases/latest' | jq -r '.tag_name')"
          flow_cli_nix_version="$(curl -s 'https://api.github.com/repos/chris-de-leon/flow-cli.nix/releases/latest' | jq -r '.tag_name')"
          echo "Flow CLI Nix Overlay version = $flow_cli_nix_version"
          echo "Flow CLI version = $flow_cli_version"
          if [ "$flow_cli_nix_version" != "$flow_cli_version" ]; then
            echo "CREATE_RELEASE=true" >> "$GITHUB_ENV"
          else
            echo "CREATE_RELEASE=false" >> "$GITHUB_ENV"
          fi

      - name: Checkout Repo
        if: ${{ env.CREATE_RELEASE == 'true' }}
        uses: actions/checkout@v3

      - name: Install Nix
        if: ${{ env.CREATE_RELEASE == 'true' }}
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Create Release(s)
        if: ${{ env.CREATE_RELEASE == 'true' }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          bash ./release.sh
